version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=some-user-name-here
      - POSTGRES_PASSWORD=fdijG(gdl.34g0)sdgg4(9GF)
      - POSTGRES_DB=some-db-name-here
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - db
      
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    ports:
      - "443:443"
    depends_on:
      - client
      - api
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet:
